plugins:
  account_anonymizer_enabled:
    default: true
    client: false
  account_anonymizer_username_prefix:
    default: "Deleted-"
    client: false
  account_anonymizer_anonymize_ip:
    default: false
    client: false
